spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserManagementService-Online_Auction_System
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    check-location: true
  springdoc:
    api-docs:
      path: /api-docs # Customizes the JSON/YAML endpoint path
      enabled: true  # Enables or disables the API documentation
    swagger-ui:
      path: /swagger-ui.html # Customizes the Swagger UI path
      enabled: true          # Enables or disables the Swagger UI
      operationsSorter: method # Sorts operations by method (get, post, etc.)
      tagsSorter: alpha      # Sorts tags alphabetically
      tryItOutEnabled: true  # Enables the "Try it out" feature
      filter: true           # Enables the filter box in the UI
    # packages-to-scan: com.example.controller # Scans specific packages for controllers (optional)
    # paths-to-match: /api/**                  # Matches specific request paths (optional)


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

    expiration-time: 3600000 # 1 hour in milliseconds
